language: android

env:
  global:
    - ADB_INSTALL_TIMEOUT=10 # minutes (2 minutes by default)

android:
  components:
    - platform-tools
    - tools

    - build-tools-23.0.2
    - android-23
    - extra
    - sys-img-armeabi-v7a-android-23
#    - sys-img-x86-android-17

script:
    - ./gradlew build connectedCheck